In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('seeds.csv')
print(data.shape)
data.head()

# splitting the dataset into dependent and independent categories
x = data.iloc[:,:7]
y = data.iloc[:,7]
print(x.shape)
print(y.shape)

data['type'].value_counts()

In [2]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler

iris = load_iris()

## 原始数据

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('Iris.csv')
print(data.shape)
data.head()

(150, 6)


Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [10]:
X=iris.data
scaler=MinMaxScaler()
X_MinMax=scaler.fit_transform(X)
print(X[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


## 归一化结果

In [11]:
print(X_MinMax[0:5])

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


## 标准化结果

In [16]:
from sklearn.preprocessing import StandardScaler 
stdsc=StandardScaler()
standard_x=stdsc.fit_transform(X)
print(standard_x[0:5])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]
